import { z } from "zod";

export const generationRequestSchema = z.object({
  prompt: z.string().trim().min(10).max(2000),
});

export const generationResponseSchema = z.object({
  config: z.string().min(1),
  commands: z.array(z.string().min(1)).min(1),
  guidance: z.array(z.string().min(1)).min(1),
});

export type GenerationData = z.infer<typeof generationResponseSchema>;
export type RawGenerationData = {
  config: string | Record<string, unknown>;
  commands?: string[];
  guidance?: string[];
};

const modelResponseSchema = z.object({
  config: z.union([z.string().min(1), z.record(z.string(), z.unknown())]),
  commands: z.array(z.string().min(1)).optional(),
  guidance: z.array(z.string().min(1)).optional(),
});

const looseModelResponseSchema = z.object({
  config: z.union([z.string(), z.record(z.string(), z.unknown())]).optional(),
  configFileContent: z.string().optional(),
  wrangler: z.string().optional(),
  wranglerJsonc: z.string().optional(),
  commands: z.union([z.array(z.string()), z.string()]).optional(),
  terminalCommands: z.union([z.array(z.string()), z.string()]).optional(),
  guidance: z.union([z.array(z.string()), z.string()]).optional(),
  steps: z.union([z.array(z.string()), z.string()]).optional(),
  nextSteps: z.union([z.array(z.string()), z.string()]).optional(),
  changes: z.union([z.array(z.string()), z.string()]).optional(),
});

type NormalizedRequirements = {
  includeNode: boolean;
  includeD1: boolean;
  includeR2: boolean;
  includeKv: boolean;
  includeAi: boolean;
  includeBrowser: boolean;
  framework?: string;
};

function slugify(value: string) {
  const slug = value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 40);

  return slug || "my-worker";
}

function uniqueName(base: string, suffix: string) {
  return `${base}-${suffix}`.replace(/--+/g, "-");
}

function hasKeyword(prompt: string, keywords: string[]) {
  return keywords.some((keyword) => prompt.includes(keyword));
}

function inferRequirements(prompt: string): NormalizedRequirements {
  const normalizedPrompt = prompt.toLowerCase();

  let framework: string | undefined = undefined;
  if (hasKeyword(normalizedPrompt, ["next.js", "nextjs"])) framework = "Next.js";
  else if (hasKeyword(normalizedPrompt, ["vue", "nuxt"])) framework = "Vue/Nuxt";
  else if (hasKeyword(normalizedPrompt, ["react", "remix"])) framework = "React";
  else if (hasKeyword(normalizedPrompt, ["hono"])) framework = "Hono";

  return {
    includeD1: hasKeyword(normalizedPrompt, ["d1", "database", "sqlite"]),
    includeR2: hasKeyword(normalizedPrompt, ["r2", "bucket", "object storage", "image storage"]),
    includeKv: hasKeyword(normalizedPrompt, ["kv", "cache", "namespace"]),
    includeAi: hasKeyword(normalizedPrompt, ["workers ai", "ai binding", "llm", "model"]),
    includeBrowser: hasKeyword(normalizedPrompt, ["browser"]),
    includeNode: hasKeyword(normalizedPrompt, ["next.js", "node", "npm", "package.json", "react", "nodejs_compat"]),
    framework,
  };
}

function buildConfig(options: {
  name: string;
  includeNode: boolean;
  includeD1: boolean;
  includeR2: boolean;
  includeKv: boolean;
  includeAi: boolean;
  includeBrowser: boolean;
}) {
  const lines = [
    "{",
    `  // Generated by Wrangler Wizard`,
    `  "name": "${options.name}",`,
    `  "compatibility_date": "2025-03-01",`,
  ];

  if (options.includeNode) {
    lines.push(`  "compatibility_flags": ["nodejs_compat"],`);
  }

  if (options.includeD1) {
    lines.push(
      "  \"d1_databases\": [",
      "    {",
      '      "binding": "DB",',
      '      "database_name": "my-database",',
      '      "database_id": "replace-with-d1-database-id"',
      "    }",
      "  ],"
    );
  }

  if (options.includeR2) {
    lines.push(
      '  "r2_buckets": [',
      "    {",
      '      "binding": "ASSETS",',
      '      "bucket_name": "my-assets"',
      "    }",
      "  ],"
    );
  }

  if (options.includeKv) {
    lines.push(
      '  "kv_namespaces": [',
      "    {",
      '      "binding": "CACHE",',
      '      "id": "replace-with-kv-namespace-id"',
      "    }",
      "  ],"
    );
  }

  if (options.includeAi) {
    lines.push(
      '  "ai": {',
      '    "binding": "AI"',
      "  },"
    );
  }

  if (options.includeBrowser) {
    lines.push(
      '  "browser": {',
      '    "binding": "BROWSER"',
      "  },"
    );
  }

  if (lines[lines.length - 1].endsWith(",")) {
    lines[lines.length - 1] = lines[lines.length - 1].slice(0, -1);
  }

  lines.push("}");

  return lines.join("\n");
}

function buildCommands(options: {
  baseName: string;
  includeD1: boolean;
  includeR2: boolean;
  includeKv: boolean;
}) {
  const commands = [`npm create cloudflare@latest ${safeCommandArg(options.baseName, "my-worker")}`, "npx wrangler deploy"];

  if (options.includeD1) {
    commands.unshift(`npx wrangler d1 create ${uniqueName(options.baseName, "db")}`);
  }

  if (options.includeR2) {
    commands.unshift(`npx wrangler r2 bucket create ${uniqueName(options.baseName, "assets")}`);
  }

  if (options.includeKv) {
    commands.unshift(`npx wrangler kv namespace create ${uniqueName(options.baseName, "cache")}`);
  }

  return commands;
}

function buildGuidance(options: {
  includeD1: boolean;
  includeR2: boolean;
  includeKv: boolean;
  includeNode: boolean;
  framework?: string;
}) {
  const steps = [
    options.framework
      ? `Run npm create cloudflare@latest <project-name> and select ${options.framework} from the templates.`
      : "Run npm create cloudflare@latest <project-name> and select your framework/template.",
    "Copy the generated wrangler.jsonc content into your project.",
  ];

  if (options.includeD1) {
    steps.push(
      "Run npx wrangler d1 create <database-name> and replace database_id with the returned UUID.",
      "Keep binding as DB and ensure database_name matches the D1 resource you created."
    );
  }

  if (options.includeR2) {
    steps.push(
      "Run npx wrangler r2 bucket create <bucket-name> and ensure bucket_name matches the created bucket."
    );
  }

  if (options.includeKv) {
    steps.push(
      "Run npx wrangler kv namespace create <namespace-name> and replace id with the returned namespace ID."
    );
  }

  if (options.includeNode) {
    steps.push("Keep compatibility_flags including nodejs_compat because Node APIs/packages were requested.");
  }

  steps.push("Run npx wrangler deploy after replacing all placeholder IDs.");

  return steps;
}

export function buildFallbackGeneration(prompt: string): GenerationData {
  const requirements = inferRequirements(prompt);
  const baseName = slugify(prompt);

  return {
    config: buildConfig({
      name: baseName,
      includeNode: requirements.includeNode,
      includeD1: requirements.includeD1,
      includeR2: requirements.includeR2,
      includeKv: requirements.includeKv,
      includeAi: requirements.includeAi,
      includeBrowser: requirements.includeBrowser,
    }),
    commands: buildCommands({
      baseName,
      includeD1: requirements.includeD1,
      includeR2: requirements.includeR2,
      includeKv: requirements.includeKv,
    }),
    guidance: buildGuidance({
      includeD1: requirements.includeD1,
      includeR2: requirements.includeR2,
      includeKv: requirements.includeKv,
      includeNode: requirements.includeNode,
      framework: requirements.framework,
    }),
  };
}

export function buildPrompt(userPrompt: string) {
  return [
    "You are an expert Cloudflare developer. Convert the user's request into two things:",
    "1. A valid wrangler.jsonc configuration file content as a single string.",
    "2. A list of terminal commands to create the required resources.",
    "",
    "Rules:",
    "- The config must be valid JSON with comments allowed (.jsonc).",
    '- Include name = "my-worker" or a sensible project-derived name.',
    '- Include compatibility_date = "2025-03-01".',
    '- Never invent real resource IDs.',
    '- Use explicit placeholders for unknown IDs, e.g. "replace-with-d1-database-id" and "replace-with-kv-namespace-id".',
    '- Never nest resources under a "bindings" object.',
    '- Use top-level arrays: d1_databases, r2_buckets, kv_namespaces.',
    '- For kv_namespaces entries use: { "binding": "CACHE", "id": "<namespace-id>" }.',
    '- For d1_databases entries use: { "binding": "DB", "database_name": "<name>", "database_id": "<id>" }.',
    '- For r2_buckets entries use: { "binding": "ASSETS", "bucket_name": "<bucket>" }.',
    '- Only use valid Cloudflare bindings: d1_databases, r2_buckets, kv_namespaces, ai, browser.',
    '- Include compatibility_flags = ["nodejs_compat"] only when the request explicitly implies Node.js APIs or packages.',
    '- Do not hallucinate bindings or resources that were not requested.',
    '- Commands must use the npx wrangler prefix.',
    '- Include a guidance array that explains exactly what the user must edit and the ordered steps to run.',
    '- Guidance should mention replacing placeholder IDs with real IDs returned by CLI commands.',
    "",
    `User request: """${userPrompt}"""`,
    "",
    "Respond only with a JSON object in this exact shape:",
    '{',
    '  "config": "string",',
    '  "commands": ["string"],',
    '  "guidance": ["string"]',
    '}',
  ].join("\n");
}

function stripCodeFences(input: string) {
  return input
    .trim()
    .replace(/^```(?:json)?\s*/i, "")
    .replace(/\s*```$/i, "");
}

function extractFirstJsonObject(input: string) {
  let start = -1;
  let depth = 0;
  let inString = false;
  let escaped = false;

  for (let index = 0; index < input.length; index += 1) {
    const char = input[index];

    if (inString) {
      if (escaped) {
        escaped = false;
        continue;
      }

      if (char === "\\") {
        escaped = true;
        continue;
      }

      if (char === '"') {
        inString = false;
      }

      continue;
    }

    if (char === '"') {
      inString = true;
      continue;
    }

    if (char === "{") {
      if (depth === 0) {
        start = index;
      }

      depth += 1;
      continue;
    }

    if (char === "}") {
      if (depth === 0) {
        continue;
      }

      depth -= 1;

      if (depth === 0 && start !== -1) {
        return input.slice(start, index + 1);
      }
    }
  }

  return null;
}

function normalizeCommands(commands: string[] | string | undefined) {
  if (!commands) {
    return null;
  }

  if (Array.isArray(commands)) {
    return commands.map((command) => command.trim()).filter(Boolean);
  }

  return commands
    .split("\n")
    .map((command) => command.trim())
    .filter(Boolean);
}

function normalizeModelOutput(parsed: unknown) {
  const loose = looseModelResponseSchema.safeParse(parsed);

  if (!loose.success) {
    return null;
  }

  const rawConfig =
    loose.data.config ?? loose.data.configFileContent ?? loose.data.wrangler ?? loose.data.wranglerJsonc;
  const commands = normalizeCommands(loose.data.commands ?? loose.data.terminalCommands);
  const guidance = normalizeCommands(
    loose.data.guidance ?? loose.data.steps ?? loose.data.nextSteps ?? loose.data.changes
  );

  if (!rawConfig) {
    return null;
  }

  const config = typeof rawConfig === "string" ? rawConfig : JSON.stringify(rawConfig, null, 2);

  return modelResponseSchema.safeParse({
    config,
    commands: commands ?? [],
    guidance: guidance ?? [],
  });
}

export function parseModelResponse(text: string) {
  const cleanedText = stripCodeFences(text);

  const parseCandidates = [cleanedText, extractFirstJsonObject(cleanedText)].filter(
    (candidate): candidate is string => Boolean(candidate)
  );

  for (const candidate of parseCandidates) {
    try {
      const parsed = JSON.parse(candidate) as unknown;
      const normalized = normalizeModelOutput(parsed);

      if (normalized?.success) {
        return normalized;
      }
    } catch {
      // Keep trying remaining parse candidates.
    }
  }

  return modelResponseSchema.safeParse(null);
}

function stripJsonComments(input: string) {
  return input
    .replace(/\/\/.*$/gm, "")
    .replace(/\/\*[\s\S]*?\*\//g, "")
    .replace(/,\s*([}\]])/g, "$1");
}

function normalizeBindingArray(value: unknown, kind: "kv" | "d1" | "r2") {
  if (!Array.isArray(value)) {
    return [] as Array<Record<string, string>>;
  }

  return value
    .filter((entry): entry is Record<string, unknown> => Boolean(entry) && typeof entry === "object")
    .map((entry) => {
      if (kind === "kv") {
        const rawId =
          typeof entry.id === "string"
            ? entry.id
            : typeof entry.namespace_id === "string"
              ? entry.namespace_id
              : "";

        const normalizedId = /^[a-f0-9]{32}$/i.test(rawId)
          ? rawId
          : "replace-with-kv-namespace-id";

        return {
          binding:
            typeof entry.binding === "string"
              ? entry.binding
              : typeof entry.name === "string"
                ? entry.name
                : "CACHE",
          id: normalizedId,
        };
      }

      if (kind === "d1") {
        const rawDbName =
          typeof entry.database_name === "string"
            ? entry.database_name
            : typeof entry.name === "string"
              ? entry.name
              : "my-database";

        const rawDatabaseId =
          typeof entry.database_id === "string"
            ? entry.database_id
            : typeof entry.id === "string"
              ? entry.id
              : "";

        const normalizedDatabaseId =
          /^[a-f0-9]{32}$/i.test(rawDatabaseId) ||
          /^[a-f0-9]{8}-[a-f0-9]{4}-[1-5][a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$/i.test(rawDatabaseId)
            ? rawDatabaseId
            : "replace-with-d1-database-id";

        return {
          binding: typeof entry.binding === "string" ? entry.binding : "DB",
          database_name: safeCommandArg(rawDbName, "my-database"),
          database_id: normalizedDatabaseId,
        };
      }

      return {
        binding: typeof entry.binding === "string" ? entry.binding : "ASSETS",
        bucket_name:
          typeof entry.bucket_name === "string"
            ? entry.bucket_name
            : typeof entry.name === "string"
              ? entry.name
              : "my-assets",
      };
    });
}

function normalizeCommandsForWrangler(commands: string[]) {
  const normalized = commands
    .map((command) => command.trim())
    .filter(Boolean)
    .map((command) => {
      if (/^npm\s+create\s+/i.test(command) || /^pnpm\s+create\s+/i.test(command) || /^yarn\s+create\s+/i.test(command)) {
        return command;
      }

      if (/^npx\s+wrangler\s+(generate|init)\b/i.test(command) || /^wrangler\s+(generate|init)\b/i.test(command)) {
        return "npm create cloudflare@latest";
      }

      if (/^npx\s+wrangler\s+config\b/i.test(command) || /^wrangler\s+config\b/i.test(command)) {
        return "";
      }

      if (/^npm\s+(i|install)\s+(-g\s+)?wrangler/i.test(command)) {
        return "";
      }

      command = command.replace(/\bwrangler\s+publish\b/gi, "wrangler deploy");
      command = command.replace(/\bwrangler\s+kv:namespace\b/gi, "wrangler kv namespace");

      if (command.startsWith("wrangler ")) {
        return `npx ${command}`;
      }

      if (!command.startsWith("npx wrangler ")) {
        return `npx wrangler ${command}`;
      }

      return command;
    });

  return Array.from(new Set(normalized.filter(Boolean)));
}

function safeCommandArg(value: string, fallback: string) {
  const cleaned = value
    .toLowerCase()
    .replace(/[^a-z0-9-]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 40);

  return cleaned || fallback;
}

function buildCanonicalCommandsFromConfig(normalized: Record<string, unknown>) {
  const commands: string[] = [];

  const workerName =
    typeof normalized.name === "string" ? safeCommandArg(normalized.name, "my-worker") : "my-worker";

  commands.push(`npm create cloudflare@latest ${workerName}`);

  const kvNamespaces = Array.isArray(normalized.kv_namespaces)
    ? normalized.kv_namespaces
    : [];

  for (const namespace of kvNamespaces) {
    if (!namespace || typeof namespace !== "object") {
      continue;
    }

    const entry = namespace as Record<string, unknown>;
    const baseName =
      typeof entry.binding === "string"
        ? entry.binding
        : typeof entry.id === "string"
          ? entry.id
          : "cache";

    commands.push(`npx wrangler kv namespace create ${safeCommandArg(baseName, "cache")}`);
  }

  const d1Databases = Array.isArray(normalized.d1_databases)
    ? normalized.d1_databases
    : [];

  for (const database of d1Databases) {
    if (!database || typeof database !== "object") {
      continue;
    }

    const entry = database as Record<string, unknown>;
    const dbName =
      typeof entry.database_name === "string"
        ? entry.database_name
        : typeof entry.binding === "string"
          ? entry.binding
          : "my-database";

    commands.push(`npx wrangler d1 create ${safeCommandArg(dbName, "my-database")}`);
  }

  const r2Buckets = Array.isArray(normalized.r2_buckets)
    ? normalized.r2_buckets
    : [];

  for (const bucket of r2Buckets) {
    if (!bucket || typeof bucket !== "object") {
      continue;
    }

    const entry = bucket as Record<string, unknown>;
    const bucketName =
      typeof entry.bucket_name === "string"
        ? entry.bucket_name
        : typeof entry.binding === "string"
          ? entry.binding
          : "my-assets";

    commands.push(`npx wrangler r2 bucket create ${safeCommandArg(bucketName, "my-assets")}`);
  }

  commands.push("npx wrangler deploy");

  return Array.from(new Set(normalizeCommandsForWrangler(commands)));
}

export function normalizeGenerationData(data: RawGenerationData, prompt: string): GenerationData {
  const requirements = inferRequirements(prompt);
  const fallback = buildFallbackGeneration(prompt);

  try {
    const configText = typeof data.config === "string" ? data.config : JSON.stringify(data.config, null, 2);
    const raw = JSON.parse(stripJsonComments(configText)) as Record<string, unknown>;
    const normalized: Record<string, unknown> = { ...raw };

    const nestedBindings =
      normalized.bindings && typeof normalized.bindings === "object"
        ? (normalized.bindings as Record<string, unknown>)
        : null;

    const kv = normalizeBindingArray(
      normalized.kv_namespaces ?? nestedBindings?.kv_namespaces,
      "kv"
    );
    const d1 = normalizeBindingArray(
      normalized.d1_databases ?? nestedBindings?.d1_databases,
      "d1"
    );
    const r2 = normalizeBindingArray(
      normalized.r2_buckets ?? nestedBindings?.r2_buckets,
      "r2"
    );

    delete normalized.bindings;

    normalized.name =
      typeof normalized.name === "string" && normalized.name.trim()
        ? normalized.name.trim()
        : "my-worker";
    normalized.compatibility_date = "2025-03-01";

    const flags = Array.isArray(normalized.compatibility_flags)
      ? normalized.compatibility_flags.filter((value): value is string => typeof value === "string")
      : [];

    if (requirements.includeNode && !flags.includes("nodejs_compat")) {
      flags.push("nodejs_compat");
    }

    if (!requirements.includeNode) {
      const filteredFlags = flags.filter((flag) => flag !== "nodejs_compat");
      flags.length = 0;
      flags.push(...filteredFlags);
    }

    if (flags.length > 0) {
      normalized.compatibility_flags = flags;
    } else {
      delete normalized.compatibility_flags;
    }

    if (requirements.includeKv || kv.length > 0) {
      normalized.kv_namespaces = kv.length > 0 ? kv : [{ binding: "CACHE", id: "replace-with-kv-namespace-id" }];
    } else {
      delete normalized.kv_namespaces;
    }

    if (requirements.includeD1 || d1.length > 0) {
      normalized.d1_databases =
        d1.length > 0
          ? d1
          : [{ binding: "DB", database_name: "my-database", database_id: "replace-with-d1-database-id" }];
    } else {
      delete normalized.d1_databases;
    }

    if (requirements.includeR2 || r2.length > 0) {
      normalized.r2_buckets = r2.length > 0 ? r2 : [{ binding: "ASSETS", bucket_name: "my-assets" }];
    } else {
      delete normalized.r2_buckets;
    }

    const canonicalCommands = buildCanonicalCommandsFromConfig(normalized);
    const aiCommands = normalizeCommandsForWrangler(data.commands ?? []);

    const finalCommands =
      canonicalCommands.length > 0 ? canonicalCommands : aiCommands.length > 0 ? aiCommands : fallback.commands;

    const canonicalGuidance = buildGuidance({
      includeD1: requirements.includeD1 || Array.isArray(normalized.d1_databases),
      includeR2: requirements.includeR2 || Array.isArray(normalized.r2_buckets),
      includeKv: requirements.includeKv || Array.isArray(normalized.kv_namespaces),
      includeNode: requirements.includeNode,
      framework: requirements.framework,
    });

    const finalGuidance = Array.from(new Set(canonicalGuidance));

    return {
      config: JSON.stringify(normalized, null, 2),
      commands: finalCommands,
      guidance: finalGuidance.length > 0 ? finalGuidance : fallback.guidance,
    };
  } catch {
    return {
      config: fallback.config,
      commands: normalizeCommandsForWrangler((data.commands ?? []).length > 0 ? (data.commands ?? []) : fallback.commands),
      guidance: fallback.guidance,
    };
  }
}